apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      project: cia
  replicas: 2
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
      - name: web1
        image: konstantinnikolaenko/dockerf
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: 
    env: prod
    owner: KostyaNikolaenko
spec:
  type: LoadBalancer
  selector:
    project: cia
  ports:
    - name: my-app-listener
      protocol: TCP
      port: 8085
      targetPort: 8080
